{% set name = "pngquant" %}
{% set version = "3.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/kornelski/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ddd8889a9c269ba454d0c5e4f7167948d55d77c4570b23f671809fd3a68b6822

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - libimagequant
    - lcms2
    - libpng

test:
  commands:
    - pngquant --version

about:
  home: https://pngquant.org/
  license: GPL-3.0-or-later
  license_file: COPYRIGHT
  summary: 'Lossy PNG compressor — pngquant command based on libimagequant library '

extra:
  recipe-maintainers:
    - izahn
