{% set name = "pngquant" %}
{% set version = "2.18.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/kornelski/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 424ff432e51dfc3cf5ff8001ad1b64198850686c5e3c26ecd477e4b69ef4fade

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - libimagequant
    - lcms2
    - libpng

test:
  commands:
    - pngquant --version

about:
  home: https://pngquant.org/
  license: GPL-3.0-or-later
  license_file: COPYRIGHT
  summary: 'Lossy PNG compressor — pngquant command based on libimagequant library '

extra:
  recipe-maintainers:
    - izahn
