{% set name = "pngquant" %}
{% set version = "2.14.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/kornelski/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6e43c7125b3ffd1dc52d1da3a352009e98a617c70c024b23ad38f0be7e3f614e

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - libimagequant
    - lcms2
    - libpng

test:
  commands:
    - pngquant --version

about:
  home: https://pngquant.org/
  license: GPL-3.0-or-later
  license_file: COPYRIGHT
  summary: 'Lossy PNG compressor — pngquant command based on libimagequant library '

extra:
  recipe-maintainers:
    - izahn
