{% set name = "pngquant" %}
{% set version = "3.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/kornelski/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 488e4587c27c7515427b231530cc070a6b123727137b32c501658cff3f8a3451

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - libimagequant
    - lcms2
    - libpng

test:
  commands:
    - pngquant --version

about:
  home: https://pngquant.org/
  license: GPL-3.0-or-later
  license_file: COPYRIGHT
  summary: 'Lossy PNG compressor — pngquant command based on libimagequant library '

extra:
  recipe-maintainers:
    - izahn
